version: "3"

services:
    users_db:
        image: mysql
        command:
            - --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: users_db
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=users_db
        ports:
            - 3306:3306
        networks:
            - users_network

networks:
    users_network:
        driver: bridge
